name: Desplegar sitio web en Github Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Hagamo checkout del repo
        uses: actions/checkout@v3

      - name: configuremo node
        uses: action/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm test

      - name: Subelo a Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${(secrets.GITHUN_TOKEN)}
          publish_dir: ./
          allow_empty_commit: true